export const SET_DEFAULT_LAYOUT_LEFT_DRAWER_SHOW = 'SET_DEFAULT_LAYOUT_LEFT_DRAWER_SHOW'
export const SET_DEFAULT_LAYOUT_RIGHT_DRAWER_SHOW = 'SET_DEFAULT_LAYOUT_RIGHT_DRAWER_SHOW'
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
